apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ml-api
  description: ML API deployed using Kubernetes + ArgoCD
  tags:
    - ml
    - kubernetes
    - platform
spec:
  type: service
  lifecycle: production
  owner: yashaswi